export const CART_ITEM_ADD = 'CART_ITEM_ADD'
export const CART_ITEM_REMOVE = 'CART_ITEM_REMOVE'
export const SAVE_SHIPPING_ADDRESS = 'SAVE_SHIPPING_ADDRESS'
export const GET_SHIPPING_FAILED = 'GET_SHIPPING_FAILED'
export const ORDER_PAYMENT_METHOD = 'ORDER_PAYMENT_METHOD'

