export const GET_SHIPPING_REQUEST = 'GET_SHIPPING_REQUEST'
export const GET_SHIPPING_SUCESS = 'GET_SHIPPING_SUCESS'
export const GET_SHIPPING_FAILED = 'GET_SHIPPING_FAILED'
export const SAVE_SHIPPING_REQUEST = 'SAVE_SHIPPING_REQUEST'
export const SAVE_SHIPPING_SUCESS = 'SAVE_SHIPPING_SUCESS'
export const SAVE_SHIPPING_FAILED = 'SAVE_SHIPPING_FAILED'

